In [1]:
%run train.ipynb

Requirement already up-to-date: librosa in /home/tamar/anaconda3/envs/ml/lib/python3.7/site-packages (0.7.2)
Requirement already up-to-date: pydub in /home/tamar/anaconda3/envs/ml/lib/python3.7/site-packages (0.23.1)
Requirement already up-to-date: pip in /home/tamar/anaconda3/envs/ml/lib/python3.7/site-packages (20.0.2)


/home/tamar/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


[[0.21044717 0.09326403 0.26200588 0.26705313 0.16722978]
 [0.20899242 0.09333589 0.26196313 0.26987877 0.16582979]
 [0.20935854 0.09332585 0.26196803 0.26838236 0.16696522]
 ...
 [0.20758775 0.09348713 0.26187529 0.27045626 0.16659357]
 [0.20938035 0.09331983 0.26196726 0.26844643 0.16688612]
 [0.21044723 0.09340195 0.26210047 0.26694633 0.16710402]]
2.613883527412865
0.6204690831556503


In [2]:
testData = get_all_features('test')
testData = testData.sample(frac=1).reset_index(drop=True)
testData

mfccs         flux  \
0   [-475.99863, 97.237366, 26.406332, 29.371502, ...  [1.9520866]   
1   [-479.07477, 64.50404, 28.022125, 32.40396, 10...  [1.4531025]   
2   [-444.9344, 50.723774, 18.369139, 16.199614, 7...  [1.4494555]   
3   [-497.0725, 90.217476, 23.172476, 24.907835, -...  [1.8387288]   
4   [-523.36505, 68.824, 23.766193, 25.582102, 1.8...  [1.4281317]   
5   [-506.16843, 65.66204, 33.70148, 43.65631, -4....  [1.5657883]   
6   [-555.3941, 77.74877, 32.772434, 44.852264, -1...  [1.6584789]   
7   [-444.4747, 61.19429, 24.238216, 19.800646, 9....   [1.375505]   
8   [-507.55, 103.88616, 29.129068, 21.95087, -14....  [1.6406921]   
9   [-495.3481, 68.46826, 18.52471, 18.044786, 1.4...  [1.4451244]   
10  [-485.5905, 63.222202, 15.867859, 20.553495, 1...  [1.5205839]   
11  [-511.18454, 91.000084, 5.5707726, 11.673856, ...  [1.5456005]   
12  [-478.53278, 65.184044, 17.451685, 21.89237, 7...  [1.5289221]   
13  [-405.18478, 97.23668, 26.406168, 29.371515, -...  [1.9520679]   
14  [-473.37433, 66.0062, 31.40292, 21.405188, 2.6...  [1.5360807]   
15  [-524.6957, 65.16414, 17.272255, 21.387983, 2....  [1.3466868]   
16  [-429.3955, 84.80725, 18.176964, 26.20142, -7....  [1.9984629]   
17  [-491.16025, 80.35386, 30.77545, 23.931852, -4...  [1.2332506]   
18  [-506.04794, 102.67349, 21.879492, 15.528565, ...  [1.7726547]   
19  [-517.8741, 69.99578, 20.949286, 19.870522, 3....  [1.3661466]   

                                     chroma_features1  \
0   [0.51993966, 0.56368417, 0.56326824, 0.4756087...   
1   [0.6883361, 0.7106556, 0.65595514, 0.65541476,...   
2   [0.59621143, 0.494852, 0.43561545, 0.4794019, ...   
3   [0.35220474, 0.4077386, 0.45091668, 0.4547681,...   
4   [0.57544285, 0.48190477, 0.5054778, 0.55131835...   
5   [0.40114653, 0.3731631, 0.48328295, 0.48039213...   
6   [0.44886807, 0.37058583, 0.36358938, 0.3548484...   
7   [0.67180896, 0.67138696, 0.61472505, 0.6156933...   
8   [0.25067693, 0.23629229, 0.25260672, 0.2458462...   
9   [0.6375735, 0.60269505, 0.5888851, 0.5831649, ...   
10  [0.6946735, 0.6309911, 0.6145359, 0.60764027, ...   
11  [0.29496777, 0.34143576, 0.434472, 0.40545973,...   
12  [0.6736648, 0.6688613, 0.60539407, 0.60239834,...   
13  [0.51994026, 0.5636445, 0.5632, 0.47556445, 0....   
14  [0.7186289, 0.74076194, 0.6371092, 0.60031646,...   
15  [0.6897519, 0.63471556, 0.5661489, 0.58655274,...   
16  [0.46460044, 0.44519487, 0.40207645, 0.3776281...   
17  [0.3120178, 0.39821157, 0.46795884, 0.4394161,...   
18  [0.3206917, 0.349603, 0.3843402, 0.3727167, 0....   
19  [0.69209796, 0.6553232, 0.57278675, 0.5818382,...   

                                     chroma_features2  \
0   [0.31744241277932217, 0.34654344375363483, 0.3...   
1   [0.36555908288773503, 0.29038736600037907, 0.3...   
2   [0.34556402520548585, 0.25663220899678424, 0.2...   
3   [0.251652654057558, 0.2636494533972556, 0.2409...   
4   [0.23129685834179017, 0.23201293380356736, 0.2...   
5   [0.2920471097086192, 0.2930405019111327, 0.290...   
6   [0.32936709750906745, 0.27402799280481394, 0.2...   
7   [0.35798398594514086, 0.30514770483534287, 0.2...   
8   [0.19641716906263423, 0.17706025103407974, 0.1...   
9   [0.35582834306033984, 0.2944865334980943, 0.27...   
10  [0.3931982878551257, 0.36561492294997605, 0.28...   
11  [0.2392854632682796, 0.2528453568810262, 0.274...   
12  [0.3421289642681023, 0.33528348089142884, 0.27...   
13  [0.31744241277932217, 0.34654344375363483, 0.3...   
14  [0.3603761612029049, 0.35836474005238905, 0.27...   
15  [0.3873371083945989, 0.3007049078416007, 0.277...   
16  [0.29015640189163744, 0.28485227585615125, 0.2...   
17  [0.25435417789748055, 0.27823698888932513, 0.2...   
18  [0.2073938701528828, 0.22265289558579782, 0.22...   
19  [0.3254149808443884, 0.28787497032090786, 0.27...   

                                     chroma_features3  class_label  
0   [0.7043935, 0.69583005, 0.72975284, 0.6737864,...            5  
1   [0.75790334, 0.64343953, 0.6564387, 0.6

In [3]:
testLabels = [[i] for i in testData['class_label']]
y_test = np.array(testLabels)

In [4]:
y_onehot_test = get_one_hot(y_test)

/home/tamar/anaconda3/envs/ml/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [5]:
ls_test = get_processed_X(testData)

In [6]:
U1, S1, V1 = pca(ls_test)
ls_test = project_data(ls_test, U, k)

In [7]:
weights = np.load('weights.npy', allow_pickle = True)

In [8]:
ls_test = np.matrix(ls_test)

a1, z2, a2, z3, h = forward_propagate(ls_test, weights[0], weights[1])
y_pred = np.array(np.argmax(h, axis=1) + 1)

In [9]:
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, y_test)]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print(accuracy)

0.35
